#!/usr/bin/env python3
"""Translate the run() body of src/AssemblePressureFix.java into JavaScript.

The Java is a DSL: 1,464 emit() calls plus a handful of conditionals, so a
source-to-source transform is both feasible and much safer than a hand port —
it cannot mistype an instruction string, and it can be re-run whenever the
Java changes rather than drifting away from it.

Every construct actually used in run() is handled below.  Anything else is
left alone, which means it will fail loudly as a JavaScript syntax error
rather than silently mistranslating.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent.parent
JAVA = REPO / "src" / "AssemblePressureFix.java"
OUT = REPO / "tools" / "avr32" / "program.js"

# Java preamble inside run() that has no JavaScript counterpart: argument
# handling, loading the properties file, and obtaining Ghidra's assembler.
# The driver does all of that instead.
PREAMBLE_END = "assembler = Assemblers.getAssembler(currentProgram);"


def transpile_line(line: str, state: dict) -> str:
    # long literals: 0x80014300L -> 0x80014300
    line = re.sub(r"\b(0x[0-9a-fA-F]+)L\b", r"\1", line)
    # Java's formatter -> the runtime's
    line = line.replace("String.format(", "StringFormat(")

    # int[] name = { ... };   ->   var name = [ ... ];
    m = re.match(r"^(\s*)int\[\]\s+(\w+)\s*=\s*\{(.*)\};\s*$", line)
    if m:
        return f"{m.group(1)}var {m.group(2)} = [{m.group(3)}];\n"

    # int[] name = table("x");   ->   var name = table("x");
    line = re.sub(r"^(\s*)int\[\]\s+(\w+)\s*=", r"\1var \2 =", line)
    # final int X = ... / int X = ... / long X = ... / boolean X = ...
    #   ->   var X = ...
    line = re.sub(r"^(\s*)(?:final\s+)?(?:int|long|boolean)\s+(\w+)\s*=",
                  r"\1var \2 =", line)

    # for (int v : sine) {  ->  indexed loop with the element bound inside,
    # so the body's own closing brace still closes the loop.
    m = re.match(r"^(\s*)for\s*\(\s*int\s+(\w+)\s*:\s*(\w+)\s*\)\s*\{\s*$", line)
    if m:
        indent, var, seq = m.groups()
        idx = f"__i{state['loops']}"
        state["loops"] += 1
        return (f"{indent}for (var {idx} = 0; {idx} < {seq}.length; {idx}++) {{\n"
                f"{indent}    var {var} = {seq}[{idx}];\n")
    return line


def main() -> None:
    lines = JAVA.read_text().splitlines(True)

    start = next(i for i, l in enumerate(lines) if "protected void run()" in l)
    preamble = next(i for i, l in enumerate(lines) if PREAMBLE_END in l)
    # The file ends with run()'s closing brace then the class's.
    end = len(lines) - 2
    body = lines[preamble + 1:end]

    state = {"loops": 0}
    converted = [transpile_line(l, state) for l in body]

    # Scan only code, not prose: a comment mentioning "a new target" is not a
    # Java constructor.
    def code_of(line: str) -> str:
        return line.split("//", 1)[0]

    leftovers = [
        (i, l.rstrip()) for i, l in enumerate(converted)
        if re.search(r"\b(int\[\]|final\s+int\s|String\.format|"
                     r"new\s+\w+\s*\(|\.isEmpty\(\)|throws\s)|"
                     r"\b0x[0-9a-fA-F]+L\b", code_of(l))
    ]
    if leftovers:
        print("untranslated Java construct(s) remain:", file=sys.stderr)
        for i, l in leftovers[:10]:
            print(f"  {i}: {l}", file=sys.stderr)
        raise SystemExit(1)

    OUT.write_text(
        "// GENERATED by tools/avr32/transpile.py from src/AssemblePressureFix.java\n"
        "// Do not edit: change the Java and re-run the transpiler.\n"
        "function assembleProgram() {\n"
        + "".join(converted)
        + "}\n"
    )
    print(f"wrote {OUT.relative_to(REPO)}")
    print(f"  {len(body)} source lines, {state['loops']} loop(s) rewritten")


if __name__ == "__main__":
    main()
