#!/usr/bin/env python3
"""Rebuild tools/factory_control_flow.txt from Ghidra listings of the base image.

    python3 tools/factory_control_flow.py <listing>... [--hex firmware/218eV3_v369_DFU.hex]

Each listing is what src/DumpDisassembly.java writes for one contiguous code
run of the factory image: "address<TAB>instruction" per line.  For v36.9 the
runs are 80002000..80014288 and 80014400..80018bf4:

    analyzeHeadless <proj> f -import firmware/218eV3_v369_DFU.hex \\
        -processor avr32:BE:32:default -noanalysis -readOnly -scriptPath src \\
        -postScript DumpDisassembly.java 80002000 80014288 run1.txt \\
        -postScript DumpDisassembly.java 80014400 80018bf4 run2.txt
    python3 tools/factory_control_flow.py run1.txt run2.txt

Two kinds of transfer are recorded.  A PC-relative branch or call (RJMP,
RCALL, BR{cc}) names its target in the instruction.  A pool call, MCALL
PC[pool], names a word in flash that holds the target; the target is read
from the hex and the pool address is kept as a third field, because a patch
that rewrites the pool word redirects that call and the old target is no
longer live from it.  Register-indirect calls (ICALL, MCALL Rn[..], MOV PC)
cannot be resolved statically and are not listed.

Targets outside the image's address span are Ghidra decoding data as
branches; they are dropped, as they were when the table was first made by
hand.  A target inside the span but in erased flash is kept: that is where
this build's caves go.
"""
from __future__ import annotations

import argparse
import hashlib
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "tools"))
import build  # noqa: E402

DIRECT = re.compile(r"^(?:RJMP|RCALL|BR\{[\w/]+\}) (0x[0-9a-f]+)$")
POOL = re.compile(r"^MCALL PC\[(0x[0-9a-f]+)\]$")
HEADER = """\
# Every factory branch/call and where it lands, as "source target", or
# "source target pool" for a call through a pool word at "pool".
# tools/build.py uses this to refuse a patch that would bury an address
# some other factory code still jumps to.  A pool call whose pool word a
# patch rewrites has been redirected, so its old target no longer counts
# as live from it.  Tied to one base image by the checksum below; the
# build fails if they disagree.
#
# Regenerated by tools/factory_control_flow.py from Ghidra listings of the
# image's code runs; see its docstring for the commands.  Register-indirect
# transfers cannot be listed and are not.
"""


def transfers(listings: list[Path], memory: dict[int, int]) -> list[tuple[int, int, int | None]]:
    def word(address: int) -> int | None:
        if any(address + i not in memory for i in range(4)):
            return None
        return int.from_bytes(bytes(memory[address + i] for i in range(4)), "big")

    low, high = min(memory), max(memory)
    found: list[tuple[int, int, int | None]] = []
    dropped = 0
    for listing in listings:
        for line in listing.read_text().splitlines():
            address, _, text = line.partition("\t")
            source = int(address, 16)
            if match := DIRECT.match(text):
                target, pool = int(match.group(1), 16), None
            elif match := POOL.match(text):
                pool = int(match.group(1), 16)
                target = word(pool)
                if target is None:
                    dropped += 1
                    continue
            else:
                continue
            if not low <= target <= high:
                dropped += 1
                continue
            found.append((source, target, pool))
    print(f"{len(found)} transfers ({sum(1 for t in found if t[2] is not None)} through "
          f"pool words), {dropped} dropped as outside the image")
    return sorted(set(found))


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("listings", nargs="+", type=Path)
    parser.add_argument("--hex", type=Path, default=REPO / "firmware" / "218eV3_v369_DFU.hex")
    parser.add_argument("--out", type=Path, default=build.CONTROL_FLOW)
    args = parser.parse_args()
    memory, _ = build.parse_hex(args.hex)
    digest = hashlib.sha256(args.hex.read_bytes()).hexdigest()   # as build.py checks it
    rows = transfers(args.listings, memory)
    lines = [HEADER.rstrip("\n"), f"factory_sha256 {digest}"]
    for source, target, pool in rows:
        lines.append(f"{source:08x} {target:08x}" + (f" {pool:08x}" if pool is not None else ""))
    args.out.write_text("\n".join(lines) + "\n")
    print(f"wrote {args.out.relative_to(REPO) if args.out.is_relative_to(REPO) else args.out}: "
          f"{len(rows)} rows for image {digest[:12]}")


if __name__ == "__main__":
    main()
