#!/usr/bin/env python3
"""Draw the icon sources for the flashers.

The page's banana on the site's background, on the plate the app expects.
The shape is Apple's: an 824 square inside 1024, and a superellipse rather
than a rounded rect, which is visibly the wrong curve beside the system icons
in the Dock.
"""
import math
import re
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
BANANA = REPO / "web" / "images" / "banana.svg"
GROUND = "#171716"          # the page's background

ICONS = [
    # file, plate, body fill, peel fill - None keeps the artwork's own colours
    ("mac/AppIcon.svg", "squircle", None, None),
]


def squircle(size=1024.0, side=824.0, n=5.0, steps=720):
    a, c = side / 2.0, size / 2.0
    pts = []
    for i in range(steps):
        t = 2.0 * math.pi * i / steps
        cs, sn = math.cos(t), math.sin(t)
        x = a * math.copysign(abs(cs) ** (2.0 / n), cs)
        y = a * math.copysign(abs(sn) ** (2.0 / n), sn)
        pts.append((c + x, c + y))
    return "M" + " L".join("%.2f,%.2f" % p for p in pts) + " Z"


def main():
    art = BANANA.read_text(encoding="utf-8")
    view = re.search(r'viewBox="([^"]+)"', art).group(1)
    style = re.search(r"<style>(.*?)</style>", art, re.S).group(1)
    inner = art.split("</defs>", 1)[1].rsplit("</svg>", 1)[0].strip()

    size, span = 1024.0, 600.0
    at = (size - span) / 2.0
    plates = {
        "squircle": '<path d="%s" fill="%s"/>' % (squircle(), GROUND),
        # Inset 32 with a 160 radius: near enough to the corners Windows 11
        # rounds its own tiles to that the icon does not look borrowed.
        "rounded": '<rect x="32" y="32" width="960" height="960" rx="160" '
                   'fill="%s"/>' % GROUND,
    }

    for name, plate, body, peel in ICONS:
        css = style
        if body:
            # .cls-1 is the fruit, .cls-2 the peel; the outline stays black.
            css = css.replace("fill: #FFDA6C;", f"fill: {body};")
            css = css.replace("fill: #fff;", f"fill: {peel};")
        out = f'''<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by tools/make-icons.py from web/images/banana.svg.  Rendered to
     every iconset size by tools/make-app.sh; do not edit by hand. -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024" width="1024" height="1024">
  <defs>
    <style>{css}</style>
  </defs>
  {plates[plate]}
  <svg x="{at:.2f}" y="{at:.2f}" width="{span:.2f}" height="{span:.2f}" viewBox="{view}">
{inner}
  </svg>
</svg>
'''
        (REPO / name).write_text(out, encoding="utf-8")
        print(f"  wrote {name}")


if __name__ == "__main__":
    main()
