#!/usr/bin/env python3
"""Emit web/generated.js: the fixed data a browser build needs.

Everything here is derived from the Python build, so there is one source of
truth and no hand-copied constants to drift.  Re-run after changing
tools/options.py, tools/build.py, src/AssemblePressureFix.java or
tools/factory_control_flow.txt.
"""

from __future__ import annotations

import base64
import json
import re
import subprocess
import sys
import tomllib
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "tools"))
import build as B          # noqa: E402
import options as O        # noqa: E402

OUT = REPO / "web" / "generated.js"


def main() -> None:
    cfg = tomllib.loads((REPO / "config" / "218e.toml").read_text())
    java = (REPO / "src" / "AssemblePressureFix.java").read_bytes()

    # The init marker hashes the assembler source itself, so a browser build
    # has to hash the identical bytes or every image would differ.  Base64
    # keeps them exact through the JS string.
    parts = [
        "// GENERATED by web/generate.py — do not edit.",
        "",
        "var GEN = {",
        f"  factorySha256: {json.dumps(cfg['firmware']['factory_sha256'])},",
        f"  version: {json.dumps(cfg['firmware'].get('version', '0.0.0'))},",
        f"  factoryKeyTable: {B.FACTORY_KEY_TABLE},",
        f"  pitchTableEntries: {B.PITCH_TABLE_ENTRIES},",
        f"  calibrationVoltsPerOctave: {B.CALIBRATION_VOLTS_PER_OCTAVE},",
        f"  internalDefaults: {json.dumps(O.INTERNAL_DEFAULTS, sort_keys=True)},",
        f"  featureMap: {json.dumps({k: list(v) for k, v in B.FEATURE_MAP.items()}, sort_keys=True)},",
        f"  enabledWhen: {json.dumps(B.ENABLED_WHEN, sort_keys=True)},",
        f"  javaSourceBase64: {json.dumps(base64.b64encode(java).decode())},",
        f"  changelog: {json.dumps((REPO / 'CHANGELOG.txt').read_text())},",
        f"  clix: {json.dumps(__import__('clix').CLIX)},",
    ]

    # Both flashers, whole.  The page substitutes the checksum and version of
    # the image it just built, so a download arrives as a bundle that flashes
    # that image without asking.  Both files are LF - the .bat too, which cmd
    # accepts - and JSON round-trips whatever the bytes are.
    for key, name in (("flasherMac",  "mac/Program218e_v3_Rewired_macOS.command"),
                      ("flasherWin",  "windows/218e_Rewired_Flasher.bat")):
        parts.append(f"  {key}: {json.dumps((REPO / name).read_bytes().decode())},")

    # The bundled tunings, preloaded into the page's slots (behind a checkbox
    # that defaults to off).  Shipped as content rather than fetched, so the
    # page stays a self-contained set of files.
    bundled = [
        "tunings/Sabat II (C-rooted).scl",
        "tunings/5-Limit JI with Septimal 7th.scl",
        "tunings/12TET.scl",
    ]
    tunings = [{"name": Path(t).name, "text": (REPO / t).read_text()} for t in bundled]
    parts.append(f"  bundledTunings: {json.dumps(tunings)},")

    # Factory control transfers, as a flat [src, dst, src, dst, ...] array —
    # about 2,700 pairs, and much smaller than re-parsing the text file.
    lines = (REPO / "tools" / "factory_control_flow.txt").read_text().splitlines()
    recorded = next(l.split()[1] for l in lines if l.startswith("factory_sha256 "))
    if recorded != cfg["firmware"]["factory_sha256"]:
        raise SystemExit("factory_control_flow.txt is for a different base image")
    flat = []
    for line in lines:
        if re.match(r"^[0-9a-f]{8} [0-9a-f]{8}$", line):
            a, b = line.split()
            flat += [int(a, 16), int(b, 16)]
    parts.append(f"  controlFlow: {json.dumps(flat)},")
    parts.append("};")
    parts.append("")
    parts.append("if (typeof module !== 'undefined' && module.exports) module.exports = GEN;")

    OUT.write_text("\n".join(parts) + "\n")

    # Bundle the assembler into web/ so the page loads only files beside it,
    # and so program.js is always the one transpiled from the current Java.
    subprocess.run([sys.executable, str(REPO / "tools" / "avr32" / "transpile.py")],
                   check=True, cwd=REPO, capture_output=True)
    bundle = REPO / "web" / "assembler.js"
    bundle.write_text("\n".join(
        (REPO / "tools" / "avr32" / name).read_text()
        for name in ("shim.js", "encoder.js", "runtime.js", "program.js")))
    print(f"  bundled assembler -> {bundle.relative_to(REPO)} "
          f"({bundle.stat().st_size // 1024} KB)")
    kb = OUT.stat().st_size // 1024
    print(f"wrote {OUT.relative_to(REPO)} ({kb} KB)")
    print(f"  {len(flat)//2} control transfers, {len(java)} bytes of assembler source")


if __name__ == "__main__":
    main()
