#!/usr/bin/env python3
"""Check the browser pipeline against the Python one across configurations.

For each config: build it with tools/build.py (producing build/build.properties)
and generate the same properties with web/buildlib.js, then compare byte for
byte.  Equality there means an identical image, because the assembler consuming
those properties is already proven identical to Ghidra.
"""
from __future__ import annotations

import json
import os
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPO / "tools"))
import options as OPTIONS  # noqa: E402

JSC = Path("/System/Library/Frameworks/JavaScriptCore.framework/Versions/A/Helpers/jsc")
TMP = REPO / "build"
SCALES = ["tunings/Sabat II (C-rooted).scl", "tunings/5-Limit JI with Septimal 7th.scl",
          "tunings/12TET.scl"]
CAL = "calibration/218e-pitch-calibration.csv"


def calibration_rows() -> list[dict]:
    rows = []
    for line in (REPO / CAL).read_text().splitlines():
        if line.startswith("#") or line.startswith("Semitone"):
            continue
        parts = line.split(";")
        rows.append({"semitone": int(parts[0]), "cents": float(parts[3])})
    return rows


# Shapes to test against rather than scales anyone would play, so they are
# generated into build/ instead of committed to tunings/, which is the library
# the page offers.  Both builders read the same bytes: the CLI off disk, the
# browser out of the text handed to it.
def fixture(name: str, text: str) -> str:
    TMP.mkdir(exist_ok=True)
    (TMP / name).write_text(text)
    return f"build/{name}"


def equal_steps(count: int, period: float) -> str:
    """A Scala file of `count` equal steps spanning `period` cents."""
    body = "".join(f" {period * k / count:.10f}\n" for k in range(1, count + 1))
    return (f"! generated by web/test_configs.py\n"
            f"{count} equal steps of {period} cents\n {count}\n" + body)


def keyboard_map(order: list[int], formal: int) -> str:
    """A .kbm naming `order` degree by degree, `formal` as the period."""
    return (f"! generated by web/test_configs.py\n {len(order)}\n 0\n 127\n"
            f" 60\n 69\n 440.0\n {formal}\n"
            + "".join(f" {d}\n" for d in order))


# Twelve degrees that repeat at a 3/1 instead of an octave.  Unmapped, which
# is the case the mapped Bohlen-Pierce config below cannot reach: the browser
# used to truncate an unmapped scale to twelve entries, throwing away the
# degree that says where it repeats, and then fell back to 1200 cents for both
# the key table and the octave controls.
NON_OCTAVE = fixture("_nonoctave.scl", equal_steps(12, 1901.9550008653874))

# 72-TET: 16.7-cent steps, which is 6 DAC units - finer than the latch's
# 8-unit match tolerance, so two distinct notes would toggle each other off.
FINE = fixture("_fine72.scl", equal_steps(72, 1200.0))
# Size zero is the format's "no mapping": every degree in order.
FINE_MAP = fixture("_fine72.kbm", keyboard_map([], 72))
# The same scale with the degrees interleaved, 0,36,1,37,...  No two ADJACENT
# keys are close - the nearest are 235 units apart - but keys two apart are one
# 72-TET step, so a gap measured along the keyboard misses the collision.
REORDERED_MAP = fixture(
    "_reorder72.kbm",
    keyboard_map([d for k in range(36) for d in (k, k + 36)], 72))

# One degree too many for a keyboard with one table entry per key.
THIRTEEN = fixture("_thirteen.scl", equal_steps(13, 1200.0))

# Comfortably spaced along the keyboard - 13 units at the closest - until key 0
# is latched an octave up, where it lands 6 units from key 1.  A gap read off
# the untransposed table calls this safe.
SPARSE_MAP = fixture("_sparse72.kbm",
                     keyboard_map([0, 71] + list(range(2, 56, 2)), 72))

# Five degrees to the period, so the anchor key sits more than an octave above
# the bottom and the shift that pins it drags the bottom entry below zero.
PENTATONIC = fixture(
    "_pentatonic.scl",
    "! generated by web/test_configs.py\nMinor pentatonic\n 5\n"
    " 300.0\n 500.0\n 700.0\n 1000.0\n 1200.0\n")
PENTATONIC_MAP = fixture("_pentatonic.kbm", keyboard_map([], 5))

# "Ratios are written with a slash, and only one."
TWO_SLASH = fixture(
    "_twoslash.scl",
    "! generated by web/test_configs.py\ntwo slashes in a ratio\n 12\n"
    + "".join(f" {100.0 * k}\n" for k in range(1, 7))
    + " 3/2/9\n" + "".join(f" {100.0 * k}\n" for k in range(8, 12)) + " 2/1\n")

# 53-TET, one degree per key: nine units between neighbours, which clears a
# tolerance of 8 on paper and not under the fingers, because the transpose the
# latch compares against moves by a unit between the two presses.
FINE53 = fixture("_fine53.scl", equal_steps(53, 1200.0))
FINE53_MAP = fixture("_fine53.kbm", keyboard_map([], 53))

# One degree to a 6/1 period: 1251 units a step, so the keyboard runs past the
# signed pitch limit long before it runs out of keys.
HIGH = fixture("_high.scl",
               "! generated by web/test_configs.py\nOne degree per 6/1 period\n"
               " 1\n 6/1\n")
HIGH_MAP = fixture("_high.kbm", keyboard_map([], 1))

# "At the end, unmapped keys may be left out": a legal map that stops early.
# The tail takes the nearest mapped degree, the same as any interior gap.
SHORT_MAP = fixture(
    "_short12.kbm",
    "! generated by web/test_configs.py\n 12\n 0\n 127\n 60\n 69\n 440.0\n"
    " 12\n 0\n 2\n 4\n 5\n 7\n")


def scala(paths: list[str]) -> list[dict]:
    return [{"name": Path(p).name, "text": (REPO / p).read_text()} for p in paths]


def mapped(pairs: list[tuple[str, str]]) -> list[dict]:
    """Scale-and-.kbm slots, in the shape the page keeps them."""
    return [{"name": Path(s).name, "text": (REPO / s).read_text(),
             "kbmName": Path(k).name, "kbmText": (REPO / k).read_text()}
            for s, k in pairs]


# name -> (toml edits, browser options)
CONFIGS = [
    ("defaults",          [], {}),
    ("arp_off",           [(r"^latching_arp = true", "latching_arp = false")],
                          {"latching_arp": False}),
    # Every knob on None: the four-way factory image the old remap switch
    # used to build in one line.
    ("knobs_off",         [(r"^latching_arp = true",
                            'latching_arp = true\nknob1 = "factory"\nknob2 = "factory"\n'
                            'knob3 = "factory"\nknob4 = "factory"')],
                          {"knob1": "factory", "knob2": "factory",
                           "knob3": "factory", "knob4": "factory"}),
    ("pressure_off",      [(r"^pressure_fix = true", "pressure_fix = false"),
                           (r"^pressure_portamento = true", "pressure_portamento = false")],
                          {"pressure_fix": False, "pressure_portamento": False}),
    ("portamento_off",    [(r"^pressure_portamento = true", "pressure_portamento = false")],
                          {"pressure_portamento": False}),
    # The jack transposer: a cave in front of the housekeeping, a fixed patch
    # over the factory's glide-index add, and a keys-per-period table the two
    # builders have to derive the same way - here from a .kbm as well.
    ("portamento_transpose", [(r'^portamento_in = "portamento"', 'portamento_in = "transpose"'),
                              (r"^alternate_tunings = false",
                               'alternate_tunings = [["tunings/diatonic7.scl", "tunings/diatonic7.kbm"], '
                               '"tunings/12TET.scl"]')],
                             {"portamento_in": "transpose",
                              "alternate_tunings": mapped([
                                  ("tunings/diatonic7.scl", "tunings/diatonic7.kbm")])
                                  + scala(["tunings/12TET.scl"])}),
    ("one_volt",          [(r"^volts_per_octave = 1.2", "volts_per_octave = 1.0")],
                          {"volts_per_octave": 1.0}),
    ("pitch_correction",  [(r"^pitch_correction = false", f'pitch_correction = "{CAL}"')],
                          {"pitch_correction": calibration_rows()}),
    # The 208c layout: the pitch table alone moves, so both builders have to
    # lay it out three entries later and zero what is under it - with the
    # flat ramp and with a measured table, whose top three rows drop off.
    ("no_offset",         [(r"^pitch_offset = true", "pitch_offset = false")],
                          {"pitch_offset": False}),
    ("no_offset_corrected", [(r"^pitch_offset = true", "pitch_offset = false"),
                             (r"^pitch_correction = false", f'pitch_correction = "{CAL}"')],
                            {"pitch_offset": False, "pitch_correction": calibration_rows()}),
    # The preset quantiser: one cave and one pool word, gated together.
    ("quantize_presets",  [(r"^quantize_presets = false", "quantize_presets = true")],
                          {"quantize_presets": True}),
    ("tunings_one",       [(r"^alternate_tunings = false",
                            'alternate_tunings = ["tunings/12TET.scl"]')],
                          {"alternate_tunings": scala(["tunings/12TET.scl"])}),
    ("tunings_three",     [(r"^alternate_tunings = false",
                            "alternate_tunings = [" + ", ".join(
                                f'"{s}"' for s in SCALES) + "]")],
                          {"alternate_tunings": scala(SCALES)}),
    # A .kbm changes the key table without touching the firmware, so the two
    # builders have to agree on the mapping as exactly as on the scale.  Three
    # shapes at once: more degrees than keys, fewer, and unmapped positions.
    ("tuning_maps",       [(r"^alternate_tunings = false",
                            'alternate_tunings = ['
                            '["tunings/24TET.scl", "tunings/24TET-full.kbm"], '
                            '["tunings/24TET.scl", "tunings/24TET-neutral.kbm"], '
                            '["tunings/diatonic7.scl", "tunings/diatonic7.kbm"]]')],
                          {"alternate_tunings": mapped([
                              ("tunings/24TET.scl", "tunings/24TET-full.kbm"),
                              ("tunings/24TET.scl", "tunings/24TET-neutral.kbm"),
                              ("tunings/diatonic7.scl", "tunings/diatonic7.kbm")])}),
    # A scale that repeats at a 3/1 rewrites the factory's own octave
    # arithmetic, so the two builders have to agree about five patch sites as
    # well as the table.  All three slots, because the period is one setting.
    # The three knob options together: knob 2's gate wraps knob 1's selector,
    # so both builders have to agree about the chain as well as the bank.
    ("knob_options",      [(r"^latching_arp = true",
                            'latching_arp = true\nknob1 = "orders"\n'
                            'knob2 = "patterns"\nknob4 = "trn"\n'
                            'arp_patterns = ["x...x...x...x...", "x.x.x.x.", ["xx..", 4]]')],
                          {"knob1": "orders", "knob2": "patterns", "knob4": "trn",
                           "arp_patterns": ["x...x...x...x...", "x.x.x.x.", ["xx..", 4]]}),
    # Swing takes the rhythm randomiser's own hook, so the two builders have to
    # agree about which of the two the pool word names.
    ("knob2_swing",       [(r"^latching_arp = true",
                            'latching_arp = true\nknob2 = "swing"')],
                          {"knob2": "swing"}),
    # Both ship ON now, so the configuration worth pinning is the one that
    # turns them OFF: that is the build whose housekeeping chain loses a call,
    # and the one the defaults no longer cover.
    ("sequencer_off",     [(r"^sequencer = true", "sequencer = false")],
                          {"sequencer": False}),
    ("clock_divide_off",  [(r"^clock_divide = true", "clock_divide = false")],
                          {"clock_divide": False}),
    ("both_off",          [(r"^sequencer = true", "sequencer = false"),
                           (r"^clock_divide = true", "clock_divide = false")],
                          {"sequencer": False, "clock_divide": False}),
    ("volatile",          [(r"^persist = true", "persist = false")],
                          {"persist": False, "unsupported_volatile": True}),
    ("volatile_bare",     [(r"^persist = true", "persist = false"),
                           (r"^sequencer = true", "sequencer = false"),
                           (r"^clock_divide = true", "clock_divide = false")],
                          {"persist": False, "sequencer": False, "clock_divide": False,
                           "unsupported_volatile": True}),
    ("volatile_seq",      [(r"^persist = true", "persist = false"),
                           (r"^clock_divide = true", "clock_divide = false")],
                          {"persist": False, "clock_divide": False,
                           "unsupported_volatile": True}),
    ("volatile_clock",    [(r"^persist = true", "persist = false"),
                           (r"^sequencer = true", "sequencer = false")],
                          {"persist": False, "sequencer": False,
                           "unsupported_volatile": True}),
    ("non_octave",        [(r"^alternate_tunings = false",
                            'alternate_tunings = ['
                            + ", ".join(['["tunings/BohlenPierce.scl", '
                                         '"tunings/BohlenPierce.kbm"]'] * 3)
                            + ']')],
                          {"alternate_tunings": mapped([
                              ("tunings/BohlenPierce.scl", "tunings/BohlenPierce.kbm")] * 3)}),
    # The unmapped twin of non_octave above.  Without a .kbm the browser used
    # to lose the scale's period entirely: 484 units to the octave control
    # instead of 767, and a key table that fell backwards at every twelfth key.
    ("non_octave_bare",   [(r"^alternate_tunings = false",
                            'alternate_tunings = ['
                            + ", ".join([f'"{NON_OCTAVE}"'] * 3) + ']')],
                          {"alternate_tunings": scala([NON_OCTAVE] * 3)}),
    # A .kbm that stops early.  Both builders used to refuse it, and did not
    # even agree on how many entries it had - the browser counts the trailing
    # newline the CLI never sees - so the tail has to fill identically now.
    ("short_map",         [(r"^alternate_tunings = false",
                            'alternate_tunings = ['
                            + ", ".join([f'["tunings/12TET.scl", "{SHORT_MAP}"]'] * 3)
                            + ']')],
                          {"alternate_tunings": mapped(
                              [("tunings/12TET.scl", SHORT_MAP)] * 3)}),
    # The far end of the pattern bank.  22 fitted, 32 is what the editor, the
    # config and the validator all allow, and the table was cut for 22.
    ("patterns_32",       [(r"^latching_arp = true",
                            'latching_arp = true\nknob2 = "patterns"\n'
                            'arp_patterns = [' + ", ".join(['"x..."'] * 32) + ']')],
                          {"knob2": "patterns", "arp_patterns": ["x..."] * 32}),
    ("historical",        [(r"^pitch_correction = false", f'pitch_correction = "{CAL}"'),
                           (r"^alternate_tunings = false",
                            "alternate_tunings = [" + ", ".join(
                                f'"{s}"' for s in SCALES) + "]")],
                          {"pitch_correction": calibration_rows(),
                           "alternate_tunings": scala(SCALES)}),
]


# Configurations BOTH builders must refuse, and the reason each must give.
# An image comparison can only check configs both sides accept: a guard present
# in one builder and missing from the other produces a perfectly ordinary image
# on the side that lacks it, matching nothing, while the comparison stays
# silent.  name -> (toml edits, browser options, CLI fragment, page fragment).
REFUSALS = [
    # Persistence is mandatory, so a config that turns it off is not a
    # configuration at all.  Both toolchains have to say so, and say it the
    # same way - the variants above build only because they ask for the
    # unsupported image by name.
    ("volatile_refused",  [(r"^persist = true", "persist = false")],
                          {"persist": False},
                          "not a supported configuration",
                          "not a supported configuration"),
    # A mapping finer than the latch can resolve.  The image is valid in every
    # other way, so nothing downstream would have caught it.
    ("fine_latch",        [(r"^alternate_tunings = false",
                            'alternate_tunings = ['
                            + ", ".join([f'["{FINE}", "{FINE_MAP}"]'] * 3) + ']')],
                          {"alternate_tunings": mapped([(FINE, FINE_MAP)] * 3)},
                          "closest two different keys", "closest two different keys"),
    # The same collision, hidden from any gap measured between adjacent keys.
    # Separate from fine_latch on purpose: adding the page's missing guard does
    # nothing for a CLI that measures the wrong gap.
    ("reordered_latch",   [(r"^alternate_tunings = false",
                            'alternate_tunings = ['
                            + ", ".join([f'["{FINE}", "{REORDERED_MAP}"]'] * 3) + ']')],
                          {"alternate_tunings": mapped([(FINE, REORDERED_MAP)] * 3)},
                          "closest two different keys", "closest two different keys"),
    # One key table entry per key, and no .kbm to map them.
    ("unmapped_thirteen", [(r"^alternate_tunings = false",
                            'alternate_tunings = ['
                            + ", ".join([f'"{THIRTEEN}"'] * 3) + ']')],
                          {"alternate_tunings": scala([THIRTEEN] * 3)},
                          "12-note scale is required", "12-note scale is required"),
    # Spaced safely across the keyboard, and not once an octave is added.
    ("transposed_latch",  [(r"^alternate_tunings = false",
                            'alternate_tunings = ['
                            + ", ".join([f'["{FINE}", "{SPARSE_MAP}"]'] * 3) + ']')],
                          {"alternate_tunings": mapped([(FINE, SPARSE_MAP)] * 3)},
                          "closest two different keys", "closest two different keys"),
    # The anchor pushes the bottom entry under zero, and the firmware reads the
    # table unsigned.
    ("negative_entry",    [(r"^alternate_tunings = false",
                            'alternate_tunings = ['
                            + ", ".join([f'["{PENTATONIC}", "{PENTATONIC_MAP}"]'] * 3)
                            + ']')],
                          {"alternate_tunings": mapped(
                              [(PENTATONIC, PENTATONIC_MAP)] * 3)},
                          "below zero", "below zero"),
    # A ratio the format does not allow.  The browser read the first two parts
    # and ignored the rest, so this built a fifth on the page and nothing at
    # all in the CLI.
    ("two_slash_ratio",   [(r"^alternate_tunings = false",
                            f'alternate_tunings = ["{TWO_SLASH}"]')],
                          {"alternate_tunings": scala([TWO_SLASH])},
                          "single slash", "single slash"),
    # Nine units apart, which the nominal comparison called safe.
    ("nominal_margin",    [(r"^alternate_tunings = false",
                            'alternate_tunings = ['
                            + ", ".join([f'["{FINE53}", "{FINE53_MAP}"]'] * 3) + ']')],
                          {"alternate_tunings": mapped([(FINE53, FINE53_MAP)] * 3)},
                          "closest two different keys", "closest two different keys"),
    # Past the signed pitch limit once the octave controls are stepped up.
    ("signed_pitch_limit", [(r"^alternate_tunings = false",
                             'alternate_tunings = ['
                             + ", ".join([f'["{HIGH}", "{HIGH_MAP}"]'] * 3) + ']')],
                           {"alternate_tunings": mapped([(HIGH, HIGH_MAP)] * 3)},
                           "signed 16-bit", "signed 16-bit"),
    # One past the bank.  The page used to leave this to the assembler, which
    # answers "Code crossed target" - true, and no use to anyone.
    ("patterns_33",       [(r"^latching_arp = true",
                            'latching_arp = true\nknob2 = "patterns"\n'
                            'arp_patterns = [' + ", ".join(['"x..."'] * 33) + ']')],
                          {"knob2": "patterns", "arp_patterns": ["x..."] * 33},
                          "one to 32 patterns", "one to 32 patterns"),
]


# build.py writes these beside the image it built, and a variant build
# overwrites them even though its hex is redirected to build/_web.hex.  Left
# alone, the last variant's metadata sits there describing the default image -
# build/VERSION naming a checksum no shipped file has.
METADATA = ("VERSION", "build.properties", "patch_manifest.txt", "tables.txt")


def snapshot() -> dict[str, bytes | None]:
    return {name: (REPO / "build" / name).read_bytes()
            if (REPO / "build" / name).exists() else None
            for name in METADATA}


def restore(saved: dict[str, bytes | None]) -> None:
    for name, content in saved.items():
        path = REPO / "build" / name
        if content is None:
            path.unlink(missing_ok=True)     # nothing was there to begin with
        else:
            path.write_bytes(content)


def prepare(base: str, name: str, edits: list) -> Path:
    """Write config/_web.toml for one variant, and refuse to guess."""
    text = base
    for pattern, replacement in edits:
        text, n = re.subn(pattern, replacement, text, flags=re.M)
        if n != 1:
            raise SystemExit(f"{name}: edit {pattern!r} matched {n} times")
    text = re.sub(r'^output_hex\s*=\s*".*"', 'output_hex     = "build/_web.hex"',
                  text, flags=re.M)
    # Strip the updater list so a variant build cannot rewrite the real
    # flashers with its own checksum.  This is asserted rather than assumed:
    # it was previously a single-line regex, the key became a multi-line array,
    # the match silently stopped happening, and every sweep quietly left the
    # shipped flashers expecting a variant image.
    text, removed = re.subn(r'^updaters?\s*=\s*(?:".*"|\[[^\]]*\])\n', "",
                            text, flags=re.M | re.S)
    if removed != 1:
        raise SystemExit("could not strip [firmware].updaters from the config — "
                         "a variant build would overwrite the real flashers")
    path = REPO / "config" / "_web.toml"
    path.write_text(text)
    return path


def run_refusals(base: str, rows: list) -> None:
    """Both builders must refuse these, and for the stated reason.

    Refusing for the wrong reason is not parity: a config rejected by the
    period check on one side and the latch check on the other agrees only by
    accident, and the guard that matters could still be missing.
    """
    for name, edits, options, cli_want, web_want in REFUSALS:
        cfg_path = prepare(base, name, edits)
        try:
            built = subprocess.run(
                [sys.executable, "tools/build.py", "--no-ghidra",
                 "--config", str(cfg_path)],
                capture_output=True, text=True, cwd=REPO)
            cli_out = (built.stdout + built.stderr).replace("\n", " ")
            cli_ok = built.returncode != 0 and cli_want in cli_out
            cli = "refused" if cli_ok else (
                "BUILT" if built.returncode == 0 else "wrong reason")

            (TMP / "_opts.json").write_text(json.dumps(options))
            js = subprocess.run(
                [str(JSC), "web/generated.js", "web/sha256.js", "web/buildlib.js",
                 "tools/avr32/encoder.js", "tools/avr32/runtime.js",
                 "tools/avr32/program.js", "web/build.js", "web/test_refusal.js",
                 "--", str(TMP / "_opts.json"), "firmware/218eV3_v369_DFU.hex"],
                capture_output=True, text=True, cwd=REPO)
            web_out = (js.stdout + js.stderr).strip()
            web_ok = web_out.startswith("REFUSED") and web_want in web_out
            web = "refused" if web_ok else (
                "BUILT" if web_out.startswith("BUILT") else "wrong reason")
            if not cli_ok:
                web = web + "  cli: " + cli_out.strip()[-90:]
            elif not web_ok:
                web = web + "  page: " + web_out[-90:]
            rows.append((name, cli, web, not (cli_ok and web_ok)))
        finally:
            cfg_path.unlink(missing_ok=True)
            (REPO / "build" / "_web.hex").unlink(missing_ok=True)


def main() -> None:
    base = (REPO / "config" / "218e.toml").read_text()
    saved = snapshot()
    rows: list[tuple[str, str, str, bool]] = []
    refused: list[tuple[str, str, str, bool]] = []
    try:
        run(base, rows)
        run_refusals(base, refused)
    finally:
        restore(saved)

    width = max(len(r[0]) for r in rows + refused)
    print(f"\n{'config'.ljust(width)}  {'build.properties':16s}  image")
    for name, result, image, _failed in rows:
        print(f"{name.ljust(width)}  {result:16s}  {image}")
    print(f"\n{'refused by both'.ljust(width)}  {'tools/build.py':16s}  the page")
    for name, cli, web, _failed in refused:
        print(f"{name.ljust(width)}  {cli:16s}  {web}")
    failures = sum(1 for r in rows + refused if r[3])
    total = len(rows) + len(refused)
    print(f"\n{total - failures}/{total} match")
    if failures:
        raise SystemExit(1)


def run(base: str, rows: list) -> None:
    for name, edits, options in CONFIGS:
        cfg_path = prepare(base, name, edits)
        try:
            # The volatile rows are unsupported images, built here only to prove
            # the two toolchains still agree on them.  run_refusals() above
            # deliberately does not lift the refusal.
            env = dict(os.environ)
            if options.get("persist") is False:
                env[OPTIONS.VOLATILE_ENV] = "1"
            built = subprocess.run(
                [sys.executable, "tools/build.py", "--no-ghidra", "--config", str(cfg_path)],
                capture_output=True, text=True, cwd=REPO, env=env)
            if built.returncode != 0:
                rows.append((name, "build.py failed", "-", True)); continue
            sha = re.search(r"SHA-256 ([0-9a-f]{64})", built.stdout).group(1)

            (TMP / "_opts.json").write_text(json.dumps(options))
            js = subprocess.run(
                # The whole stack: the harness asks WEBBUILD.build() for the
                # properties now instead of deriving the flags a second time,
                # so it needs build.js and the assembler it pulls in.
                [str(JSC), "web/generated.js", "web/sha256.js", "web/buildlib.js",
                 "tools/avr32/encoder.js", "tools/avr32/runtime.js",
                 "tools/avr32/program.js", "web/build.js",
                 "web/test_properties.js", "--", str(TMP / "_opts.json"),
                 "firmware/218eV3_v369_DFU.hex", str(TMP / "build.properties")],
                capture_output=True, text=True, cwd=REPO)
            out = (js.stdout + js.stderr).strip()
            props_ok = out.startswith("IDENTICAL")

            # And the whole image, not just the settings that feed it.
            (TMP / "_opts.json").write_text(json.dumps(options))
            e2e = subprocess.run(
                [str(JSC), "web/generated.js", "web/sha256.js", "web/buildlib.js",
                 "tools/avr32/encoder.js", "tools/avr32/runtime.js",
                 "tools/avr32/program.js", "web/build.js", "web/test_e2e.js", "--",
                 str(TMP / "_opts.json"), "firmware/218eV3_v369_DFU.hex"],
                capture_output=True, text=True, cwd=REPO)
            m = re.search(r"SHA ([0-9a-f]{64})", e2e.stdout)
            web_sha = m.group(1) if m else (e2e.stdout + e2e.stderr).strip()[:60]
            image_ok = web_sha == sha
            rows.append((name,
                         "identical" if props_ok else out.replace("\n", "\n      "),
                         sha[:12] if image_ok else "MISMATCH " + str(web_sha)[:20],
                         not (props_ok and image_ok)))
        finally:
            cfg_path.unlink(missing_ok=True)
            (REPO / "build" / "_web.hex").unlink(missing_ok=True)


if __name__ == "__main__":
    main()
